services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy 
      chroma:
        condition: service_started 
    env_file:
      - .env
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
  
  chroma:
    image: chromadb/chroma:0.4.24
    container_name: chroma
    ports:
      - "8001:8000"
    volumes:
      - chromadata:/chroma/.chroma/index
    networks:
      - elastic

volumes:
  esdata:
    driver: local
  chromadata:
    driver: local

networks:
  elastic:
    driver: bridge